<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYzx0xlQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYzx0xlQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYzx0xlQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYzx0xlQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYzx0xlQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yzx0xlQ',
    'container.build_id' => '810a5f6f',
    'container.build_time' => 1784722956,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYzx0xlQ');
