<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAq4uuaO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAq4uuaO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAq4uuaO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAq4uuaO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAq4uuaO\App_KernelDevDebugContainer([
    'container.build_hash' => 'Aq4uuaO',
    'container.build_id' => '72971eaf',
    'container.build_time' => 1784710293,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAq4uuaO');
